using GDriveBackup.Core.Constants;
using GDriveBackup.Core.Extensions;
using GDriveBackup.Crosscutting.Configuration;
using GDriveBackup.Crosscutting.Logging;
using Google.Apis.Auth.OAuth2;
using Google.Apis.Drive.v3;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using PdfSharp.Pdf;
using PdfSharp.Pdf.IO;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Threading.Tasks;

namespace GDriveBackup.ServiceLayer.GoogleDrive.Downloader
{
    /// <summary>
    /// Executes automatic split/export flow for oversized Google Docs.
    /// Split parts are generated by copying the source document and trimming content
    /// ranges, so native formatting/tables/images are preserved in exported PDFs.
    /// </summary>
    public class GoogleDriveLargeGdocAutoSplitter
    {
        private const int MaxRecursiveSplitDepth = 4;
        private const int MinRecursiveSplitCharsPerPart = 20000;

        private sealed class BlockInfo
        {
            public int StartIndex { get; set; }
            public int EndIndex { get; set; }
            public int EstimatedLength { get; set; }
            public bool IsHeading1 { get; set; }
        }

        private sealed class SplitChunkPlan
        {
            public int KeepStartIndex { get; set; }
            public int KeepEndIndex { get; set; }
        }

        private sealed class SplitPlan
        {
            public int DocumentEndIndex { get; set; }
            public List<SplitChunkPlan> Chunks { get; } = new List<SplitChunkPlan>();
        }

        private static class SplitMode
        {
            public const string Heading1 = "Heading1";
            public const string SizeOnly = "SizeOnly";
        }

        public class LargeGdocSplitCandidate
        {
            public Google.Apis.Drive.v3.Data.File SourceFile { get; set; }
            public string LocalPath { get; set; }
            public string FailureReason { get; set; }
            public string AttemptedExportMimeType { get; set; }
        }

        public class LargeGdocSplitExecutionItem
        {
            public string SourceFileId { get; set; }
            public string SourceFileName { get; set; }
            public string Status { get; set; }
            public string Details { get; set; }
            public int ChunkCount { get; set; }
            public List<string> CreatedPartDocIds { get; set; } = new List<string>();
            public string StitchedPdfPath { get; set; }
        }

        public class LargeGdocSplitExecutionResult
        {
            public string RunId { get; set; }
            public DateTime GeneratedUtc { get; set; }
            public bool DryRun { get; set; }
            public int Candidates { get; set; }
            public int Attempted { get; set; }
            public int Succeeded { get; set; }
            public int Failed { get; set; }
            public string ReportPath { get; set; }
            public List<string> ResolvedSourceFileIds { get; set; } = new List<string>();
            public List<LargeGdocSplitExecutionItem> Items { get; set; } = new List<LargeGdocSplitExecutionItem>();
        }

        private readonly DriveService _driveService;
        private readonly GoogleCredential _credential;
        private readonly IApplicationLogger _logger;

        public GoogleDriveLargeGdocAutoSplitter(DriveService driveService, GoogleCredential credential, IApplicationLogger logger)
        {
            this._driveService = driveService ?? throw new ArgumentNullException(nameof(driveService));
            this._credential = credential ?? throw new ArgumentNullException(nameof(credential));
            this._logger = logger ?? throw new ArgumentNullException(nameof(logger));
        }

        public async Task<LargeGdocSplitExecutionResult> ExecuteAsync(
            IList<LargeGdocSplitCandidate> candidates,
            string runId)
        {
            var result = new LargeGdocSplitExecutionResult
            {
                RunId = runId,
                GeneratedUtc = DateTime.UtcNow,
                DryRun = false
            };

            var settings = ApplicationSettings.GetInstance();

            if (candidates == null || candidates.Count <= 0)
            {
                result.Candidates = 0;
                return await this.WriteExecutionReportAsync(result).ConfigureAwait(false);
            }

            var effectiveCandidates = candidates
                .Where(c => GoogleDriveDownloaderGdocForLargeFiles.IsOversizedGdocExportFailure(
                    c.SourceFile,
                    c.AttemptedExportMimeType,
                    false,
                    c.FailureReason))
                .ToList();

            result.Candidates = effectiveCandidates.Count;

            foreach (var candidate in effectiveCandidates)
            {
                var item = new LargeGdocSplitExecutionItem
                {
                    SourceFileId = candidate.SourceFile.Id,
                    SourceFileName = candidate.SourceFile.Name
                };
                result.Items.Add(item);
                result.Attempted++;

                try
                {
                    var plan = await this.BuildSplitPlanAsync(
                        candidate.SourceFile.Id,
                        settings.LargeGdocSplitMode,
                        settings.LargeGdocMaxCharsPerPart).ConfigureAwait(false);
                    item.ChunkCount = plan.Chunks.Count;

                    if (plan.Chunks.Count <= 0)
                    {
                        item.Status = "failed";
                        item.Details = "No content chunks produced.";
                        result.Failed++;
                        continue;
                    }

                    var partCounter = 1;
                    var stitchedPartFiles = new List<(string SequenceKey, string FilePath)>();
                    foreach (var chunk in plan.Chunks)
                    {
                        var partTitle = $"{candidate.SourceFile.Name} - split {partCounter:00}";
                        var partDocId = await this.CopyDocumentAsync(candidate.SourceFile.Id, partTitle).ConfigureAwait(false);
                        item.CreatedPartDocIds.Add(partDocId);

                        await this.TrimDocumentToRangeAsync(
                                partDocId,
                                chunk.KeepStartIndex,
                                chunk.KeepEndIndex,
                                plan.DocumentEndIndex)
                            .ConfigureAwait(false);
                        var exported = await this.ExportPartWithRecursiveSplitAsync(
                                partDocId,
                                partTitle,
                                candidate.LocalPath,
                                settings,
                                settings.LargeGdocMaxCharsPerPart,
                                0,
                                item,
                                $"{partCounter:00}",
                                stitchedPartFiles)
                            .ConfigureAwait(false);
                        if (!exported)
                        {
                            throw new InvalidOperationException(
                                $"Export failed for split part [{partTitle}] after recursive splitting attempts.");
                        }

                        partCounter++;
                    }

                    var stitchedPdfPath = this.BuildStitchedOutputPdfPath(candidate.LocalPath, candidate.SourceFile.Name);
                    this.MergePdfs(
                        stitchedPartFiles
                            .OrderBy(part => part.SequenceKey, StringComparer.Ordinal)
                            .Select(part => part.FilePath)
                            .ToList(),
                        stitchedPdfPath);
                    item.StitchedPdfPath = stitchedPdfPath;

                    item.Status = "succeeded";
                    item.Details = $"Created/exported [{item.ChunkCount}] split parts and stitched into [{stitchedPdfPath}].";
                    result.Succeeded++;
                    result.ResolvedSourceFileIds.Add(candidate.SourceFile.Id);
                }
                catch (Exception ex)
                {
                    item.Status = "failed";
                    item.Details = ex.Message;
                    result.Failed++;
                    this._logger.Error(
                        $"RunId [{runId}] auto-split failed for [{candidate.SourceFile?.Name}] (Id [{candidate.SourceFile?.Id}]).",
                        ex);
                }
            }

            return await this.WriteExecutionReportAsync(result).ConfigureAwait(false);
        }

        private async Task<bool> ExportPartWithRecursiveSplitAsync(
            string documentId,
            string title,
            string localPath,
            ApplicationSettings settings,
            int maxCharsPerPart,
            int recursionDepth,
            LargeGdocSplitExecutionItem executionItem,
            string sequenceKeyPrefix,
            IList<(string SequenceKey, string FilePath)> stitchedPartFiles)
        {
            var exportResult = await this.TryExportDocumentAsPdfAsync(documentId, title, localPath).ConfigureAwait(false);
            if (exportResult.Succeeded)
            {
                if (!string.IsNullOrWhiteSpace(exportResult.OutputFilePath))
                {
                    stitchedPartFiles.Add((sequenceKeyPrefix, exportResult.OutputFilePath));
                }

                if (!settings.KeepTemporarySplitDocs)
                {
                    await this.TryDeleteDocumentAsync(documentId).ConfigureAwait(false);
                }

                return true;
            }

            if (!exportResult.IsTooLargeExportFailure)
            {
                this._logger.Error(
                    $"Auto-split part export failed for [{title}] without size-limit reason. Reason [{exportResult.FailureReason}].");
                return false;
            }

            if (recursionDepth >= MaxRecursiveSplitDepth)
            {
                this._logger.Warn(
                    $"Auto-split recursion depth reached for [{title}] (DocId [{documentId}]).");
                return false;
            }

            var nextMaxCharsPerPart = Math.Max(
                MinRecursiveSplitCharsPerPart,
                Math.Max(1, maxCharsPerPart / 2));

            if (nextMaxCharsPerPart >= maxCharsPerPart)
            {
                this._logger.Warn(
                    $"Auto-split cannot reduce chunk size further for [{title}] (DocId [{documentId}]).");
                return false;
            }

            this._logger.Warn(
                $"Auto-split retry: split part [{title}] (DocId [{documentId}]) still too large. Splitting again with MaxCharsPerPart [{nextMaxCharsPerPart}] at recursion depth [{recursionDepth + 1}].");

            // For parts that are still too large, force size-only splitting.
            // This intentionally ignores heading boundaries to guarantee smaller chunks.
            var childPlan = await this.BuildSplitPlanAsync(documentId, SplitMode.SizeOnly, nextMaxCharsPerPart).ConfigureAwait(false);
            if (childPlan.Chunks.Count <= 1)
            {
                this._logger.Warn(
                    $"Auto-split could not produce multiple child chunks for [{title}] (DocId [{documentId}]).");
                return false;
            }

            var subPartCounter = 1;
            var allChildrenExported = true;
            foreach (var childChunk in childPlan.Chunks)
            {
                var childTitle = $"{title}.{subPartCounter:00}";
                var childDocId = await this.CopyDocumentAsync(documentId, childTitle).ConfigureAwait(false);
                executionItem.CreatedPartDocIds.Add(childDocId);

                await this.TrimDocumentToRangeAsync(
                        childDocId,
                        childChunk.KeepStartIndex,
                        childChunk.KeepEndIndex,
                        childPlan.DocumentEndIndex)
                    .ConfigureAwait(false);

                var childExported = await this.ExportPartWithRecursiveSplitAsync(
                        childDocId,
                        childTitle,
                        localPath,
                        settings,
                        nextMaxCharsPerPart,
                        recursionDepth + 1,
                        executionItem,
                        $"{sequenceKeyPrefix}.{subPartCounter:00}",
                        stitchedPartFiles)
                    .ConfigureAwait(false);
                if (!childExported)
                {
                    allChildrenExported = false;
                }

                subPartCounter++;
            }

            if (!settings.KeepTemporarySplitDocs)
            {
                await this.TryDeleteDocumentAsync(documentId).ConfigureAwait(false);
            }

            return allChildrenExported;
        }

        private async Task<(bool Succeeded, bool IsTooLargeExportFailure, string FailureReason, string OutputFilePath)> TryExportDocumentAsPdfAsync(
            string documentId,
            string documentName,
            string localPath)
        {
            var exported = true;
            var isTooLargeFailure = false;
            var failureReason = string.Empty;
            var outputFilePath = Path.Combine(
                localPath,
                Path.ChangeExtension(documentName.ToValidFileName().ReplaceSpaceCharacters(), FileExtensionConstants.Pdf));

            var downloadFile = new Google.Apis.Drive.v3.Data.File
            {
                Id = documentId,
                Name = documentName,
                MimeType = MimeTypeConstants.Gdoc
            };

            var downloader = new GoogleDriveDownloaderGdoc(this._driveService);
            downloader.OnFailed = (failedLocalPath, failedLocalExt, attemptedExportMimeType, failedFile, isRetryable, reason) =>
            {
                exported = false;
                failureReason = reason ?? string.Empty;
                isTooLargeFailure = GoogleDriveDownloaderGdocForLargeFiles.IsOversizedGdocExportFailure(
                    failedFile,
                    attemptedExportMimeType,
                    isRetryable,
                    reason);
            };

            await downloader.DownloadFileAsync(localPath, downloadFile).ConfigureAwait(false);
            return (exported, isTooLargeFailure, failureReason, outputFilePath);
        }

        private async Task TryDeleteDocumentAsync(string documentId)
        {
            try
            {
                await this._driveService.Files.Delete(documentId).ExecuteAsync().ConfigureAwait(false);
            }
            catch (Exception ex)
            {
                this._logger.Warn($"Failed to delete temporary split document [{documentId}].", ex);
            }
        }

        private string BuildStitchedOutputPdfPath(string localPath, string sourceFileName)
        {
            return Path.Combine(
                localPath,
                Path.ChangeExtension(
                    sourceFileName.ToValidFileName().ReplaceSpaceCharacters(),
                    FileExtensionConstants.Pdf));
        }

        private void MergePdfs(IList<string> inputFiles, string outputFile)
        {
            if (inputFiles == null || inputFiles.Count <= 0)
            {
                throw new InvalidOperationException("No split part PDFs available to stitch.");
            }

            var outputDirectory = Path.GetDirectoryName(outputFile);
            if (!string.IsNullOrWhiteSpace(outputDirectory))
            {
                Directory.CreateDirectory(outputDirectory);
            }

            var tempOutput = $"{outputFile}.merge.{Guid.NewGuid():N}.partial";
            var mergedDocument = new PdfDocument();

            try
            {
                foreach (var inputFile in inputFiles)
                {
                    if (!File.Exists(inputFile))
                    {
                        throw new FileNotFoundException("Split part PDF not found.", inputFile);
                    }

                    using (var partDocument = PdfReader.Open(inputFile, PdfDocumentOpenMode.Import))
                    {
                        for (var i = 0; i < partDocument.PageCount; i++)
                        {
                            mergedDocument.AddPage(partDocument.Pages[i]);
                        }
                    }
                }

                mergedDocument.Save(tempOutput);
                mergedDocument.Close();

                if (File.Exists(outputFile))
                {
                    File.Delete(outputFile);
                }

                File.Move(tempOutput, outputFile);
            }
            finally
            {
                mergedDocument.Dispose();
                if (File.Exists(tempOutput))
                {
                    File.Delete(tempOutput);
                }
            }
        }

        private async Task<LargeGdocSplitExecutionResult> WriteExecutionReportAsync(LargeGdocSplitExecutionResult result)
        {
            var reportDir = Path.Combine(ApplicationSettings.GetInstance().ExportPath, "_reports");
            Directory.CreateDirectory(reportDir);
            var reportPath = Path.Combine(reportDir, $"large-gdoc-split-execution-{result.RunId}.json");
            File.WriteAllText(reportPath, JsonConvert.SerializeObject(result, Formatting.Indented));
            result.ReportPath = reportPath;
            return result;
        }

        private async Task<SplitPlan> BuildSplitPlanAsync(string docId, string splitMode, int maxCharsPerPart)
        {
            var document = await this.GetDocumentAsync(docId).ConfigureAwait(false);
            var contentArray = document["body"]?["content"] as JArray;
            if (contentArray == null || contentArray.Count <= 0)
            {
                return new SplitPlan();
            }

            var blocks = this.ReadTopLevelBlocks(contentArray);
            if (blocks.Count <= 0)
            {
                return new SplitPlan();
            }

            var plan = new SplitPlan
            {
                DocumentEndIndex = blocks.Max(block => block.EndIndex)
            };

            var currentChunk = new List<BlockInfo>();
            var currentLength = 0;

            foreach (var block in blocks)
            {
                // Start a new split at heading boundaries to keep semantic sections together.
                if (string.Equals(splitMode, SplitMode.Heading1, StringComparison.OrdinalIgnoreCase)
                    && block.IsHeading1
                    && currentChunk.Count > 0)
                {
                    plan.Chunks.Add(this.CreateChunkPlan(currentChunk));
                    currentChunk.Clear();
                    currentLength = 0;
                }

                if (currentLength + block.EstimatedLength > maxCharsPerPart
                    && currentChunk.Count > 0)
                {
                    plan.Chunks.Add(this.CreateChunkPlan(currentChunk));
                    currentChunk.Clear();
                    currentLength = 0;
                }

                currentChunk.Add(block);
                currentLength += block.EstimatedLength;
            }

            if (currentChunk.Count > 0)
            {
                plan.Chunks.Add(this.CreateChunkPlan(currentChunk));
            }

            // Size-only fallback for very large blocks: if normal block-based packing still results in a single
            // chunk larger than the target, force index-range slicing by maxCharsPerPart.
            if (string.Equals(splitMode, SplitMode.SizeOnly, StringComparison.OrdinalIgnoreCase))
            {
                var targetMax = Math.Max(1, maxCharsPerPart);
                var singleChunkTooLarge = plan.Chunks.Count == 1
                                          && (plan.Chunks[0].KeepEndIndex - plan.Chunks[0].KeepStartIndex) > targetMax;
                if (singleChunkTooLarge)
                {
                    var forcedPlan = this.BuildForcedSizeOnlyPlan(plan.DocumentEndIndex, targetMax);
                    if (forcedPlan.Chunks.Count > 1)
                    {
                        return forcedPlan;
                    }
                }
            }

            return plan;
        }

        private SplitPlan BuildForcedSizeOnlyPlan(int documentEndIndex, int maxCharsPerPart)
        {
            var plan = new SplitPlan
            {
                DocumentEndIndex = Math.Max(2, documentEndIndex)
            };

            var keepStart = 1;
            var lastContentIndex = Math.Max(1, plan.DocumentEndIndex - 1);
            while (keepStart < lastContentIndex)
            {
                var keepEnd = Math.Min(lastContentIndex, keepStart + maxCharsPerPart);
                if (keepEnd <= keepStart)
                {
                    break;
                }

                plan.Chunks.Add(new SplitChunkPlan
                {
                    KeepStartIndex = keepStart,
                    KeepEndIndex = keepEnd
                });

                keepStart = keepEnd;
            }

            return plan;
        }

        private List<BlockInfo> ReadTopLevelBlocks(JArray contentArray)
        {
            var blocks = new List<BlockInfo>();

            foreach (var content in contentArray)
            {
                var startIndex = (int?)content["startIndex"] ?? 0;
                var endIndex = (int?)content["endIndex"] ?? 0;
                if (startIndex <= 0 || endIndex <= startIndex)
                {
                    continue;
                }

                var paragraph = content["paragraph"];
                var isHeading1 = paragraph != null
                                 && string.Equals(
                                     paragraph["paragraphStyle"]?["namedStyleType"]?.ToString(),
                                     "HEADING_1",
                                     StringComparison.OrdinalIgnoreCase);

                var estimatedLength = Math.Max(1, endIndex - startIndex);
                if (paragraph != null)
                {
                    var paragraphText = this.ReadParagraphText(paragraph);
                    if (!string.IsNullOrWhiteSpace(paragraphText))
                    {
                        estimatedLength = paragraphText.Length;
                    }
                }

                blocks.Add(new BlockInfo
                {
                    StartIndex = startIndex,
                    EndIndex = endIndex,
                    EstimatedLength = estimatedLength,
                    IsHeading1 = isHeading1
                });
            }

            return blocks;
        }

        private SplitChunkPlan CreateChunkPlan(IList<BlockInfo> blocks)
        {
            return new SplitChunkPlan
            {
                KeepStartIndex = blocks.Min(block => block.StartIndex),
                KeepEndIndex = blocks.Max(block => block.EndIndex)
            };
        }

        private string ReadParagraphText(JToken paragraph)
        {
            var elements = paragraph["elements"] as JArray;
            if (elements == null)
            {
                return string.Empty;
            }

            var sb = new StringBuilder();
            foreach (var element in elements)
            {
                var textRun = element["textRun"];
                var text = textRun?["content"]?.ToString();
                if (!string.IsNullOrEmpty(text))
                {
                    sb.Append(text);
                }
            }

            // Keep paragraph boundaries when the API payload does not include an explicit newline.
            if (sb.Length > 0 && sb[sb.Length - 1] != '\n')
            {
                sb.Append('\n');
            }

            return sb.ToString();
        }

        private async Task<JObject> GetDocumentAsync(string docId)
        {
            using (var client = await this.CreateAuthorizedHttpClientAsync().ConfigureAwait(false))
            {
                var response = await client.GetAsync($"https://docs.googleapis.com/v1/documents/{docId}").ConfigureAwait(false);
                await this.EnsureSuccessWithBodyAsync(response, $"GET documents/{docId}").ConfigureAwait(false);
                var json = await response.Content.ReadAsStringAsync().ConfigureAwait(false);
                return JObject.Parse(json);
            }
        }

        private async Task<string> CopyDocumentAsync(string sourceDocumentId, string title)
        {
            var copyRequest = this._driveService.Files.Copy(
                new Google.Apis.Drive.v3.Data.File
                {
                    Name = title
                },
                sourceDocumentId);
            copyRequest.Fields = "id";
            var copied = await copyRequest.ExecuteAsync().ConfigureAwait(false);
            return copied.Id;
        }

        private async Task TrimDocumentToRangeAsync(
            string documentId,
            int keepStartIndex,
            int keepEndIndex,
            int documentEndIndex)
        {
            using (var client = await this.CreateAuthorizedHttpClientAsync().ConfigureAwait(false))
            {
                var effectiveDocumentEnd = Math.Max(2, documentEndIndex);
                var requests = new JArray();

                // Delete the tail first so front indexes remain stable.
                var tailDeleteEndExclusive = Math.Max(1, effectiveDocumentEnd - 1);
                if (keepEndIndex < tailDeleteEndExclusive)
                {
                    requests.Add(
                        new JObject
                        {
                            ["deleteContentRange"] = new JObject
                            {
                                ["range"] = new JObject
                                {
                                    ["startIndex"] = keepEndIndex,
                                    ["endIndex"] = tailDeleteEndExclusive
                                }
                            }
                        });
                }

                // Then delete the head.
                if (keepStartIndex > 1)
                {
                    requests.Add(
                        new JObject
                        {
                            ["deleteContentRange"] = new JObject
                            {
                                ["range"] = new JObject
                                {
                                    ["startIndex"] = 1,
                                    ["endIndex"] = keepStartIndex
                                }
                            }
                        });
                }

                var payload = new JObject
                {
                    ["requests"] = requests
                };

                if (!requests.Any())
                {
                    return;
                }

                var response = await client.PostAsync(
                    $"https://docs.googleapis.com/v1/documents/{documentId}:batchUpdate",
                    new StringContent(payload.ToString(Formatting.None), Encoding.UTF8, "application/json")).ConfigureAwait(false);
                await this.EnsureSuccessWithBodyAsync(response, $"POST documents/{documentId}:batchUpdate").ConfigureAwait(false);
            }
        }

        private async Task EnsureSuccessWithBodyAsync(HttpResponseMessage response, string operation)
        {
            if (response.IsSuccessStatusCode)
            {
                return;
            }

            var responseBody = response.Content == null
                ? string.Empty
                : await response.Content.ReadAsStringAsync().ConfigureAwait(false);

            // Keep the full API response in the exception message so logs clearly explain
            // whether this is scope, permission-sharing, or API-enablement related.
            throw new HttpRequestException(
                $"Docs API call failed during [{operation}] with status [{(int)response.StatusCode} {response.StatusCode}]. ResponseBody [{responseBody}]");
        }

        private async Task<HttpClient> CreateAuthorizedHttpClientAsync()
        {
            var client = new HttpClient
            {
                Timeout = TimeSpan.FromSeconds(ApplicationSettings.GetInstance().DriveApiRequestTimeoutSeconds)
            };

            var token = await this._credential.UnderlyingCredential
                .GetAccessTokenForRequestAsync()
                .ConfigureAwait(false);
            client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
            return client;
        }
    }
}
