using GDriveBackup.Core.Constants;
using GDriveBackup.Crosscutting.Configuration;
using GDriveBackup.Crosscutting.Logging;
using Google.Apis.Auth.OAuth2;
using Google.Apis.Drive.v3;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Threading.Tasks;

namespace GDriveBackup.ServiceLayer.GoogleDrive.Downloader
{
    /// <summary>
    /// Executes automatic split/export flow for oversized Google Docs.
    /// Split parts are generated by copying the source document and trimming content
    /// ranges, so native formatting/tables/images are preserved in exported PDFs.
    /// </summary>
    public class GoogleDriveLargeGdocAutoSplitter
    {
        private sealed class BlockInfo
        {
            public int StartIndex { get; set; }
            public int EndIndex { get; set; }
            public int EstimatedLength { get; set; }
            public bool IsHeading1 { get; set; }
        }

        private sealed class SplitChunkPlan
        {
            public int KeepStartIndex { get; set; }
            public int KeepEndIndex { get; set; }
        }

        private sealed class SplitPlan
        {
            public int DocumentEndIndex { get; set; }
            public List<SplitChunkPlan> Chunks { get; } = new List<SplitChunkPlan>();
        }

        public class LargeGdocSplitCandidate
        {
            public Google.Apis.Drive.v3.Data.File SourceFile { get; set; }
            public string LocalPath { get; set; }
            public string FailureReason { get; set; }
            public string AttemptedExportMimeType { get; set; }
        }

        public class LargeGdocSplitExecutionItem
        {
            public string SourceFileId { get; set; }
            public string SourceFileName { get; set; }
            public string Status { get; set; }
            public string Details { get; set; }
            public int ChunkCount { get; set; }
            public List<string> CreatedPartDocIds { get; set; } = new List<string>();
        }

        public class LargeGdocSplitExecutionResult
        {
            public string RunId { get; set; }
            public DateTime GeneratedUtc { get; set; }
            public bool DryRun { get; set; }
            public int Candidates { get; set; }
            public int Attempted { get; set; }
            public int Succeeded { get; set; }
            public int Failed { get; set; }
            public string ReportPath { get; set; }
            public List<string> ResolvedSourceFileIds { get; set; } = new List<string>();
            public List<LargeGdocSplitExecutionItem> Items { get; set; } = new List<LargeGdocSplitExecutionItem>();
        }

        private readonly DriveService _driveService;
        private readonly GoogleCredential _credential;
        private readonly IApplicationLogger _logger;

        public GoogleDriveLargeGdocAutoSplitter(DriveService driveService, GoogleCredential credential, IApplicationLogger logger)
        {
            this._driveService = driveService ?? throw new ArgumentNullException(nameof(driveService));
            this._credential = credential ?? throw new ArgumentNullException(nameof(credential));
            this._logger = logger ?? throw new ArgumentNullException(nameof(logger));
        }

        public async Task<LargeGdocSplitExecutionResult> ExecuteAsync(
            IList<LargeGdocSplitCandidate> candidates,
            string runId)
        {
            var result = new LargeGdocSplitExecutionResult
            {
                RunId = runId,
                GeneratedUtc = DateTime.UtcNow,
                DryRun = false
            };

            var settings = ApplicationSettings.GetInstance();

            if (candidates == null || candidates.Count <= 0)
            {
                result.Candidates = 0;
                return await this.WriteExecutionReportAsync(result).ConfigureAwait(false);
            }

            var effectiveCandidates = candidates
                .Where(c => GoogleDriveDownloaderGdocForLargeFiles.IsOversizedGdocExportFailure(
                    c.SourceFile,
                    c.AttemptedExportMimeType,
                    false,
                    c.FailureReason))
                .ToList();

            result.Candidates = effectiveCandidates.Count;

            foreach (var candidate in effectiveCandidates)
            {
                var item = new LargeGdocSplitExecutionItem
                {
                    SourceFileId = candidate.SourceFile.Id,
                    SourceFileName = candidate.SourceFile.Name
                };
                result.Items.Add(item);
                result.Attempted++;

                try
                {
                    var plan = await this.BuildSplitPlanAsync(
                        candidate.SourceFile.Id,
                        settings.LargeGdocSplitMode,
                        settings.LargeGdocMaxCharsPerPart).ConfigureAwait(false);
                    item.ChunkCount = plan.Chunks.Count;

                    if (plan.Chunks.Count <= 0)
                    {
                        item.Status = "failed";
                        item.Details = "No content chunks produced.";
                        result.Failed++;
                        continue;
                    }

                    var partCounter = 1;
                    foreach (var chunk in plan.Chunks)
                    {
                        var partTitle = $"{candidate.SourceFile.Name} - split {partCounter:00}";
                        var partDocId = await this.CopyDocumentAsync(candidate.SourceFile.Id, partTitle).ConfigureAwait(false);
                        item.CreatedPartDocIds.Add(partDocId);

                        await this.TrimDocumentToRangeAsync(
                                partDocId,
                                chunk.KeepStartIndex,
                                chunk.KeepEndIndex,
                                plan.DocumentEndIndex)
                            .ConfigureAwait(false);

                        // Reuse existing GDoc downloader so split parts follow the same local naming/path rules.
                        var partFile = new Google.Apis.Drive.v3.Data.File
                        {
                            Id = partDocId,
                            Name = partTitle,
                            MimeType = MimeTypeConstants.Gdoc
                        };

                        await new GoogleDriveDownloaderGdoc(this._driveService)
                            .DownloadFileAsync(candidate.LocalPath, partFile)
                            .ConfigureAwait(false);

                        if (!settings.KeepTemporarySplitDocs)
                        {
                            await this._driveService.Files.Delete(partDocId).ExecuteAsync().ConfigureAwait(false);
                        }

                        partCounter++;
                    }

                    item.Status = "succeeded";
                    item.Details = $"Created/exported [{item.ChunkCount}] split parts.";
                    result.Succeeded++;
                    result.ResolvedSourceFileIds.Add(candidate.SourceFile.Id);
                }
                catch (Exception ex)
                {
                    item.Status = "failed";
                    item.Details = ex.Message;
                    result.Failed++;
                    this._logger.Error(
                        $"RunId [{runId}] auto-split failed for [{candidate.SourceFile?.Name}] (Id [{candidate.SourceFile?.Id}]).",
                        ex);
                }
            }

            return await this.WriteExecutionReportAsync(result).ConfigureAwait(false);
        }

        private async Task<LargeGdocSplitExecutionResult> WriteExecutionReportAsync(LargeGdocSplitExecutionResult result)
        {
            var reportDir = Path.Combine(ApplicationSettings.GetInstance().ExportPath, "_reports");
            Directory.CreateDirectory(reportDir);
            var reportPath = Path.Combine(reportDir, $"large-gdoc-split-execution-{result.RunId}.json");
            File.WriteAllText(reportPath, JsonConvert.SerializeObject(result, Formatting.Indented));
            result.ReportPath = reportPath;
            return result;
        }

        private async Task<SplitPlan> BuildSplitPlanAsync(string docId, string splitMode, int maxCharsPerPart)
        {
            var document = await this.GetDocumentAsync(docId).ConfigureAwait(false);
            var contentArray = document["body"]?["content"] as JArray;
            if (contentArray == null || contentArray.Count <= 0)
            {
                return new SplitPlan();
            }

            var blocks = this.ReadTopLevelBlocks(contentArray);
            if (blocks.Count <= 0)
            {
                return new SplitPlan();
            }

            var plan = new SplitPlan
            {
                DocumentEndIndex = blocks.Max(block => block.EndIndex)
            };

            var currentChunk = new List<BlockInfo>();
            var currentLength = 0;

            foreach (var block in blocks)
            {
                // Start a new split at heading boundaries to keep semantic sections together.
                if (string.Equals(splitMode, "Heading1", StringComparison.OrdinalIgnoreCase)
                    && block.IsHeading1
                    && currentChunk.Count > 0)
                {
                    plan.Chunks.Add(this.CreateChunkPlan(currentChunk));
                    currentChunk.Clear();
                    currentLength = 0;
                }

                if (currentLength + block.EstimatedLength > maxCharsPerPart
                    && currentChunk.Count > 0)
                {
                    plan.Chunks.Add(this.CreateChunkPlan(currentChunk));
                    currentChunk.Clear();
                    currentLength = 0;
                }

                currentChunk.Add(block);
                currentLength += block.EstimatedLength;
            }

            if (currentChunk.Count > 0)
            {
                plan.Chunks.Add(this.CreateChunkPlan(currentChunk));
            }

            return plan;
        }

        private List<BlockInfo> ReadTopLevelBlocks(JArray contentArray)
        {
            var blocks = new List<BlockInfo>();

            foreach (var content in contentArray)
            {
                var startIndex = (int?)content["startIndex"] ?? 0;
                var endIndex = (int?)content["endIndex"] ?? 0;
                if (startIndex <= 0 || endIndex <= startIndex)
                {
                    continue;
                }

                var paragraph = content["paragraph"];
                var isHeading1 = paragraph != null
                                 && string.Equals(
                                     paragraph["paragraphStyle"]?["namedStyleType"]?.ToString(),
                                     "HEADING_1",
                                     StringComparison.OrdinalIgnoreCase);

                var estimatedLength = Math.Max(1, endIndex - startIndex);
                if (paragraph != null)
                {
                    var paragraphText = this.ReadParagraphText(paragraph);
                    if (!string.IsNullOrWhiteSpace(paragraphText))
                    {
                        estimatedLength = paragraphText.Length;
                    }
                }

                blocks.Add(new BlockInfo
                {
                    StartIndex = startIndex,
                    EndIndex = endIndex,
                    EstimatedLength = estimatedLength,
                    IsHeading1 = isHeading1
                });
            }

            return blocks;
        }

        private SplitChunkPlan CreateChunkPlan(IList<BlockInfo> blocks)
        {
            return new SplitChunkPlan
            {
                KeepStartIndex = blocks.Min(block => block.StartIndex),
                KeepEndIndex = blocks.Max(block => block.EndIndex)
            };
        }

        private string ReadParagraphText(JToken paragraph)
        {
            var elements = paragraph["elements"] as JArray;
            if (elements == null)
            {
                return string.Empty;
            }

            var sb = new StringBuilder();
            foreach (var element in elements)
            {
                var textRun = element["textRun"];
                var text = textRun?["content"]?.ToString();
                if (!string.IsNullOrEmpty(text))
                {
                    sb.Append(text);
                }
            }

            // Keep paragraph boundaries when the API payload does not include an explicit newline.
            if (sb.Length > 0 && sb[sb.Length - 1] != '\n')
            {
                sb.Append('\n');
            }

            return sb.ToString();
        }

        private async Task<JObject> GetDocumentAsync(string docId)
        {
            using (var client = await this.CreateAuthorizedHttpClientAsync().ConfigureAwait(false))
            {
                var response = await client.GetAsync($"https://docs.googleapis.com/v1/documents/{docId}").ConfigureAwait(false);
                await this.EnsureSuccessWithBodyAsync(response, $"GET documents/{docId}").ConfigureAwait(false);
                var json = await response.Content.ReadAsStringAsync().ConfigureAwait(false);
                return JObject.Parse(json);
            }
        }

        private async Task<string> CopyDocumentAsync(string sourceDocumentId, string title)
        {
            var copyRequest = this._driveService.Files.Copy(
                new Google.Apis.Drive.v3.Data.File
                {
                    Name = title
                },
                sourceDocumentId);
            copyRequest.Fields = "id";
            var copied = await copyRequest.ExecuteAsync().ConfigureAwait(false);
            return copied.Id;
        }

        private async Task TrimDocumentToRangeAsync(
            string documentId,
            int keepStartIndex,
            int keepEndIndex,
            int documentEndIndex)
        {
            using (var client = await this.CreateAuthorizedHttpClientAsync().ConfigureAwait(false))
            {
                var effectiveDocumentEnd = Math.Max(2, documentEndIndex);
                var requests = new JArray();

                // Delete the tail first so front indexes remain stable.
                var tailDeleteEndExclusive = Math.Max(1, effectiveDocumentEnd - 1);
                if (keepEndIndex < tailDeleteEndExclusive)
                {
                    requests.Add(
                        new JObject
                        {
                            ["deleteContentRange"] = new JObject
                            {
                                ["range"] = new JObject
                                {
                                    ["startIndex"] = keepEndIndex,
                                    ["endIndex"] = tailDeleteEndExclusive
                                }
                            }
                        });
                }

                // Then delete the head.
                if (keepStartIndex > 1)
                {
                    requests.Add(
                        new JObject
                        {
                            ["deleteContentRange"] = new JObject
                            {
                                ["range"] = new JObject
                                {
                                    ["startIndex"] = 1,
                                    ["endIndex"] = keepStartIndex
                                }
                            }
                        });
                }

                var payload = new JObject
                {
                    ["requests"] = requests
                };

                if (!requests.Any())
                {
                    return;
                }

                var response = await client.PostAsync(
                    $"https://docs.googleapis.com/v1/documents/{documentId}:batchUpdate",
                    new StringContent(payload.ToString(Formatting.None), Encoding.UTF8, "application/json")).ConfigureAwait(false);
                await this.EnsureSuccessWithBodyAsync(response, $"POST documents/{documentId}:batchUpdate").ConfigureAwait(false);
            }
        }

        private async Task EnsureSuccessWithBodyAsync(HttpResponseMessage response, string operation)
        {
            if (response.IsSuccessStatusCode)
            {
                return;
            }

            var responseBody = response.Content == null
                ? string.Empty
                : await response.Content.ReadAsStringAsync().ConfigureAwait(false);

            // Keep the full API response in the exception message so logs clearly explain
            // whether this is scope, permission-sharing, or API-enablement related.
            throw new HttpRequestException(
                $"Docs API call failed during [{operation}] with status [{(int)response.StatusCode} {response.StatusCode}]. ResponseBody [{responseBody}]");
        }

        private async Task<HttpClient> CreateAuthorizedHttpClientAsync()
        {
            var client = new HttpClient
            {
                Timeout = TimeSpan.FromSeconds(ApplicationSettings.GetInstance().DriveApiRequestTimeoutSeconds)
            };

            var token = await this._credential.UnderlyingCredential
                .GetAccessTokenForRequestAsync()
                .ConfigureAwait(false);
            client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
            return client;
        }
    }
}
